allowBuilds:
  '@apollo/protobufjs': false
  '@datadog/pprof': false
  '@ffmpeg-installer/linux-x64': false
  '@firebase/util': false
  '@serialport/bindings-cpp': false
  '@vercel/git-hooks': false
  argon2: false
  bcrypt: true
  ejs: false
  es5-ext: false
  esbuild: false
  ffmpeg-static: true
  leveldown: false
  microtime: false
  msgpackr-extract: false
  nice-napi: false
  oracledb: false
  phantomjs-prebuilt: true
  protobufjs: false
  sharp: false
  unix-dgram: false
  zeromq: false
minimumReleaseAge: 2880
