allowBuilds:
  '@apollo/protobufjs': false
  '@datadog/pprof': false
  '@ffmpeg-installer/linux-x64': false
  '@firebase/util': false
  '@serialport/bindings-cpp': false
  '@vercel/git-hooks': false
  argon2: false
  bcrypt: true
  ejs: false
  es5-ext: false
  esbuild: false
  ffmpeg-static: true
  leveldown: false
  microtime: false
  msgpackr-extract: false
  nice-napi: false
  oracledb: false
  phantomjs-prebuilt: false
  protobufjs: false
  sharp: false
  unix-dgram: false
  zeromq: false
minimumReleaseAge: 2880
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: latest
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
minimumReleaseAgeExclude:
  - vite-plus
  - '@voidzero-dev/*'
  - oxlint
  - '@oxlint/*'
  - oxlint-tsgolint
  - '@oxlint-tsgolint/*'
  - oxfmt
  - '@oxfmt/*'
