import { defineConfig } from 'vite-plus';

const nodeVersion = parseInt(process.versions.node.split('.')[0], 10);

export default defineConfig({
  test: {
    // Mirror jest.config.js: testEnvironment "node".
    environment: 'node',
    // Provide describe/it/expect/beforeAll/afterEach as globals, matching jest.
    globals: true,
    // Mirror jest testMatch ['<rootDir>/test/*(*.)@(spec|test).js?(x)'].
    include: ['test/*.{spec,test}.{js,jsx}'],
    // The integration suite forks long-running fixtures (jest.setTimeout(200_000)).
    testTimeout: 200_000,
    hookTimeout: 200_000,
    // The ported @vercel/nft suite mocks graceful-fs and ../out/analyze via
    // vi.mock and expects those mocks to apply to the CJS modules under
    // ../out/*. Inline the built output and graceful-fs so Vitest's module
    // runner — not Node's native require — loads them and the mocks take hold.
    server: {
      deps: {
        inline: [/[\\/]out[\\/]/, /graceful-fs/],
      },
    },
    coverage: {
      // Mirror jest collectCoverageFrom: ['out/**/*.js'].
      include: ['out/**/*.js'],
      reporter: ['html', 'lcov'],
      thresholds: {
        branches: 87.25,
        functions: nodeVersion >= 26 ? 95.75 : 96.25,
        lines: 90.5,
        // jest used statements: -249 (allow up to 249 uncovered statements);
        // Vitest has no negative-threshold form, so this is intentionally
        // dropped — see the migration notes in the PR description.
        statements: 0,
      },
    },
  },
  staged: {
    '*': 'vp check --fix',
  },
  // Type-aware lint (tsgolint) builds its own TS program and does not honour
  // tsconfig `exclude`, so it pulls in the thousands of `@vercel/nft` test
  // fixtures under `test/{unit,integration,fixtures,ecmascript}` — many of
  // which are intentionally malformed (syntax-error fixtures, `output.js`
  // files that are JSON, legacy import assertions). Authoritative type checking
  // is done by `tsc` via `vp run build` (tsconfig already excludes `test/**`),
  // so we keep `vp lint`/`vp check` as fast syntactic/stylistic oxlint scoped
  // by `.oxlintrc.json` and leave type-aware checks to the build.
  lint: {
    // The @vercel/nft test fixtures are third-party/generated sources that are
    // intentionally weird (webpack bundles, syntax-error fixtures, `output.js`
    // files that are JSON, the generated ecmascript data tables). They are
    // trace inputs, not project code, so they are excluded from linting.
    ignorePatterns: [
      'out/**',
      'dist/**',
      'coverage/**',
      'crates/**',
      'test/fixtures/**',
      'test/integration/**',
      'test/unit/**',
      'test/ecmascript/**',
    ],
    options: { typeAware: false, typeCheck: false },
  },
  fmt: {
    endOfLine: 'lf',
    tabWidth: 2,
    printWidth: 80,
    useTabs: false,
    singleQuote: true,
    sortPackageJson: {},
    ignorePatterns: [
      'node_modules',
      'out',
      'dist',
      'coverage',
      'test/**/dist',
      'test/**/actual.js',
      'test/ecmascript',
      'test/fixtures',
      'test/integration',
      'test/unit',
      'package-lock.json',
      'yarn.lock',
      'pnpm-lock.yaml',
      // Generated by `napi build`; do not hand-format (it is regenerated).
      'crates/nftrs_napi/index.js',
      'crates/nftrs_napi/index.d.ts',
    ],
  },
});
