version: 2
jobs:
  test-linux:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: No-op
          command: echo 'do nothing'
workflows:
  version: 2
  test:
    jobs:
      - test-linux
