/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Trace the runtime file dependencies of the given entry `files`. */
export declare function nodeFileTrace(files: Array<string>, options?: NodeFileTraceOptions | undefined | null): NodeFileTraceResult

/**
 * Options for [`node_file_trace`]. Mirrors a subset of `@vercel/nft`'s
 * `NodeFileTraceOptions`; unrecognized fields are ignored.
 */
export interface NodeFileTraceOptions {
  /** Base path for the returned file list. Defaults to `process.cwd()`. */
  base?: string
  /** Working directory for `process.cwd()` resolution. Defaults to `base`. */
  processCwd?: string
  /** Max dependency depth to follow (`undefined` = unlimited). */
  depth?: number
  /** Whether to resolve `.ts`/`.tsx` files. Defaults to `true`. */
  ts?: boolean
  /** Whether to compute asset/file references. Defaults to `true`. */
  analysis?: boolean
  /** Active resolution conditions (default `["node"]`). */
  conditions?: Array<string>
  /** Only resolve via `exports` (no legacy `main` fallback). */
  exportsOnly?: boolean
  /** Treat `module-sync` as auto-selectable for wildcard subpaths. */
  moduleSyncCatchall?: boolean
  /** `paths` option: specifier (or `prefix/`) → target path. */
  paths?: Record<string, string>
}

/**
 * Why a file is included: its reason `type`s and parent files. Mirrors a
 * `@vercel/nft` `NodeFileTraceReasons` entry.
 */
export interface NodeFileTraceReason {
  /** Reason types: `initial` / `dependency` / `asset` / `resolve` / `sharedlib`. */
  type: Array<string>
  /** The files (relative to `base`) that referenced this one. */
  parents: Array<string>
}

/**
 * Result of [`node_file_trace`], matching `@vercel/nft`'s
 * `NodeFileTraceResult` shape (`fileList` / `esmFileList` / `reasons` /
 * `warnings`).
 */
export interface NodeFileTraceResult {
  /** All files (relative to `base`) needed at runtime. */
  fileList: Array<string>
  /** The subset of `file_list` that is ESM. */
  esmFileList: Array<string>
  /** Non-fatal warnings encountered during tracing. */
  warnings: Array<string>
  /** The reasons graph: file (relative to `base`) → why it's included. */
  reasons: Record<string, NodeFileTraceReason>
}

/** The `@nftrs/core` package version. */
export declare function version(): string
