/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Trace the runtime file dependencies of the given entry `files`. */
export declare function nodeFileTrace(files: Array<string>, options?: NodeFileTraceOptions | undefined | null): NodeFileTraceResult

/**
 * Options for [`node_file_trace`]. Mirrors a subset of `@vercel/nft`'s
 * `NodeFileTraceOptions`; unrecognized fields are ignored.
 */
export interface NodeFileTraceOptions {
  /** Base path for the returned file list. Defaults to `process.cwd()`. */
  base?: string
  /** Max dependency depth to follow (`undefined` = unlimited). */
  depth?: number
  /** Whether to resolve `.ts`/`.tsx` files. Defaults to `true`. */
  ts?: boolean
}

/**
 * Result of [`node_file_trace`], matching `@vercel/nft`'s
 * `NodeFileTraceResult` shape (`reasons` is added with #22).
 */
export interface NodeFileTraceResult {
  /** All files (relative to `base`) needed at runtime. */
  fileList: Array<string>
  /** The subset of `file_list` that is ESM. */
  esmFileList: Array<string>
  /** Non-fatal warnings encountered during tracing. */
  warnings: Array<string>
}

/** The `@nftrs/core` package version. */
export declare function version(): string
