/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Trace the runtime file dependencies of the given entry `files`.
 *
 * Takes the options as a raw object so the `resolve` / `ignore` callbacks
 * (JS functions, which can't live in a `#[napi(object)]` struct) can be
 * pulled out and invoked synchronously during the trace.
 */
export declare function nodeFileTrace(files: Array<string>, options?: {
  base?: string
  processCwd?: string
  depth?: number
  ts?: boolean
  analysis?: boolean
  conditions?: Array<string>
  exportsOnly?: boolean
  moduleSyncCatchall?: boolean
  paths?: Record<string, string>
  resolve?: (specifier: string, parent: string, cjs: boolean) => string | Array<string> | false | undefined
  ignore?: (path: string) => boolean
  }): NodeFileTraceResult

/**
 * Why a file is included: its reason `type`s and parent files. Mirrors a
 * `@vercel/nft` `NodeFileTraceReasons` entry.
 */
export interface NodeFileTraceReason {
  /** Reason types: `initial` / `dependency` / `asset` / `resolve` / `sharedlib`. */
  type: Array<string>
  /** The files (relative to `base`) that referenced this one. */
  parents: Array<string>
}

/**
 * Result of [`node_file_trace`], matching `@vercel/nft`'s
 * `NodeFileTraceResult` shape (`fileList` / `esmFileList` / `reasons` /
 * `warnings`).
 */
export interface NodeFileTraceResult {
  /** All files (relative to `base`) needed at runtime. */
  fileList: Array<string>
  /** The subset of `file_list` that is ESM. */
  esmFileList: Array<string>
  /** Non-fatal warnings encountered during tracing. */
  warnings: Array<string>
  /** The reasons graph: file (relative to `base`) → why it's included. */
  reasons: Record<string, NodeFileTraceReason>
}

/** The `@nftrs/core` package version. */
export declare function version(): string
