[
  "package.json",
  "test/unit/depth/asset-2.txt",
  "test/unit/depth/asset.txt",
  "test/unit/depth/child-1.js",
  "test/unit/depth/child-2.js",
  "test/unit/depth/child-3.js",
  "test/unit/depth/input.js",
  "test/unit/depth/style.module.css"
]